[package]
name = "kanna-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
nestify = "0.3.3"
serde = { version = "1.0.199", features = ["derive"] }
